imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:     stream
            level:    debug
            channels: ['!event']
            handler:  nested
        nested:
            type:      stream
            path:      'php://stderr'
            level:     debug
            channels:  ['!event']
            formatter: monolog.formatter.line
        console:
            type:     console
            bubble:   false
            channels: ['!event', '!doctrine']
