parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    security_lib.strength:
        class: SecurityLib\Strength
        arguments:
            - 5

    random_lib:
        class: RandomLib\Factory

    security_lib.factory:
        class: RandomLib\Factory
        factory: ['@random_lib', getGenerator]
        arguments: ['@security_lib.strength']

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        public:    false
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            -
                db_table: sessions
                db_username: "%database_user%"
                db_password: "%database_password%"

    PodYardBundle\:
        resource: '../../src/PodYardBundle/*'
        exclude: '../../src/PodYardBundle/{Entity,Repository,Tests}'

    PodYardBundle\Controller\:
        resource: '../../src/PodYardBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    fos_user.user_manager.default:
        class: PodYardBundle\Domain\UserManager
        arguments:
            - "@fos_user.util.password_updater"
            - "@fos_user.util.canonical_fields_updater"
            - "@fos_user.object_manager"
            - '%fos_user.model.user.class%'
