version: '3.2'
networks:
  private:
  public:
    external:
      name: traefik_webgateway
secrets:
  db_host:
    file: ./secrets/db_host
  db_name:
    file: ./secrets/db_name
  db_port:
    file: ./secrets/db_port
  db_root_password:
    file: ./secrets/db_root_password
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  sf_secret:
    file: ./secrets/sf_secret
  sf_enc_key:
    file: ./secrets/sf_enc_key
volumes:
  db-datastore:
  composer:
services:
  mariadb:
    image: mariadb:10.1
    secrets:
      - db_host
      - db_name
      - db_port
      - db_root_password
      - db_user
      - db_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_name
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - private
    restart: always
    volumes:
      - db-datastore:/var/lib/mysql
      - ./mariadb/config-file.cnf:/etc/mysql/conf.d/config-file.cnf:ro
  nginx:
    image: nginx:alpine
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}_nginx
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:dashtainer.localhost
      - traefik.port=8080
    networks:
      - private
      - public
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./../public/:/var/www/public:delegated
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        SYSTEM_PACKAGES: git openssh-client php7.2-curl php7.2-intl php7.2-json php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-xml php-pear php7.2-zip php-xdebug
        PEAR_PACKAGES: ~
        PECL_PACKAGES: ~
        COMPOSER_INSTALL: 1
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment:
      - APP_ENV=dev
    secrets:
      - db_host
      - db_name
      - db_port
      - db_user
      - db_password
      - sf_secret
      - sf_enc_key
    networks:
      - private
    volumes:
      - composer:/.composer
      - ./php/php.ini:/etc/php/7.2/fpm/conf.d/zzzz_custom.ini:ro
      - ./php/php-cli.ini:/etc/php/7.2/cli/conf.d/zzzz_custom.ini:ro
      - ./php/xdebug.ini:/etc/php/7.2/fpm/conf.d/zzzz_xdebug.ini:ro
      - ./php/xdebug-cli.ini:/etc/php/7.2/cli/conf.d/zzzz_xdebug.ini:ro
      - ./php/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf:ro
      - ./../:/var/www:cached
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_PLUGINS
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}_adminer
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:adminer.dashtainer.localhost
    networks:
      - private
      - public
