project_name: dashtainer
version: 1.0

services:
    php-fpm70-1:
        service_type: php-fpm
        name: php-fpm70-1
        settings:
            version: 7.0
            modules:
                system: []
                php:
                    - intl
                    - mysql
                    - xml
                pear: []
                pecl: []
            ini:
                display_errors: On
                error_reporting: -1
                session.save_path: /var/lib/php/sessions
                opcache.enable: 1
                opcache.enable_cli: 1
                opcache.revalidate_freq: 0
                opcache.validate_timestamps: 1
                opcache.memory_consumption: 256
                opcache.max_accelerated_files: 40000
                opcache.interned_strings_buffer: 16
                opcache.fast_shutdown: 1
                date.timezone: UTC
            fpm_pool_ini:
                listen: 0.0.0.0:9000
                pm: dynamic
                pm.max_children: 5
                pm.start_servers: 2
                pm.min_spare_servers: 1
                pm.max_spare_servers: 3
                security.limit_extensions: .php
            tools:
                xdebug:
                    install: 1
                    ini:
                        xdebug.default_enable: 1
                        xdebug.remote_autostart: 1
                        xdebug.remote_connect_back: 0
                        xdebug.remote_enable: 1
                        xdebug.remote_handler: dbgp
                        xdebug.remote_port: 9000
                        xdebug.remote_host: docker.for.mac.host.internal
                composer:
                    install: 1
                blackfire:
                    install: 1
                    settings:
                        BLACKFIRE_SERVER_ID: blackfire_server_id
                        BLACKFIRE_SERVER_TOKEN: blackfire_server_token
        networks:
            - web
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    apache-1:
        service_type: apache
        name: apache-1
        settings:
            modules:
                system:
                    - vim
                apache_enabled:
                    - http2
                    - mpm_event
                    - proxy_fcgi
                    - rewrite
                apache_disabled:
                    - mpm_prefork
                    - mpm_worker
            vhost:
                server_name: apache-vhost.localhost
                server_aliases:
                    - www.apache-vhost.localhost
                document_root: /var/www/vhost/public
                set_env_if:
                    - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
                protocols:
                    - h2
                    - http/1.1
                directories:
                    fm:
                        provider: filesmatch
                        path: \.php$
                        set_handler: 'proxy:fcgi://127.0.0.1:9000'
                        set_env:
                            - 'APP_ENV dev'
                    dir:
                        provider: directory
                        path: /var/www/vhost/public
                        directory_index: app.php
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_overrides:
                            - All
                        requires:
                            - 'all granted'
                        rewrites:
                            rewrite_1:
                                rewrite_base: ''
                                comment: ''
                                rewrite_cond:
                                    - '%{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$'
                                rewrite_rule:
                                    - '^(.*) - [E=BASE:%1]'
                            rewrite_2:
                                rewrite_base: ''
                                comment: ''
                                rewrite_cond:
                                    - '%{ENV:REDIRECT_STATUS} ^$'
                                rewrite_rule:
                                    - '^app\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]'
                            rewrite_3:
                                rewrite_base: ''
                                comment: ''
                                rewrite_cond:
                                    - '%{REQUEST_FILENAME} -f'
                                rewrite_rule:
                                    - '.? - [L]'
                            rewrite_4:
                                rewrite_base: ''
                                comment: ''
                                rewrite_rule:
                                    - '.? %{ENV:BASE}/app.php [L]'
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:apache-vhost.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    nginx-1:
        service_type: nginx
        name: nginx-1
        settings:
            modules:
                system: []
            core:
                client_max_body_size: 10m
                client_body_buffer_size: 128k
            proxy:
                proxy_redirect: off
                proxy_connect_timeout: 600s
                proxy_send_timeout: 600s
                proxy_read_timeout: 600s
                proxy_buffers: 4 256k
                proxy_buffer_size: 128k
                proxy_http_version: 1.0
                proxy_set_header:
                    - Host $host
                    - X-Real-IP $remote_addr
                    - X-Forwarded-For $proxy_add_x_forwarded_for
                proxy_headers_hash_bucket_size: 64
            server:
                rewrite_www_to_non_www: 1
                rewrite_to_https: 1
                server_names:
                    - nginx-vhost.localhost
                root: /var/www/vhost/public
                indexs:
                    - index.html
                    - index.php
                client_max_body_size: 1m
                sendfile: 'off'
                locations:
                    base:
                        path: /
                        root: /var/www/vhost/public
                        autoindex: 'off'
                        internal: 0
                        index:
                            - app.php
                        try_files:
                            - $uri
                            - $uri/
                            - /app.php$is_args$args
                    dev:
                        path: '~ ^/(app_dev|config)\.php(/|$)'
                        root: /var/www/vhost/public
                        autoindex: 'off'
                        internal: 0
                        try_files:
                            - $uri
                            - $uri/
                            - /app_dev.php$is_args$args
                        fastcgi_pass: '127.0.0.1:9000'
                        fastcgi_index: app_dev.php
                        fastcgi_split_path_info: '^(.+\.php)(/.*)$'
                        fastcgi_params:
                            - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                            - 'DOCUMENT_ROOT $realpath_root'
                            - 'APP_ENV dev'
                        sets:
                            - '$path_info $fastcgi_path_info'
                    prod:
                        path: '~ ^/app\.php(/|$)'
                        root: /var/www/vhost/public
                        autoindex: 'off'
                        internal: 1
                        try_files:
                            - $uri
                            - $uri/
                            - /app.php$is_args$args
                        fastcgi_pass: '127.0.0.1:9000'
                        fastcgi_index: app.php
                        fastcgi_split_path_info: '^(.+\.php)(/.*)$'
                        fastcgi_params:
                            - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                            - 'DOCUMENT_ROOT $realpath_root'
                            - 'APP_ENV prod'
                        sets:
                            - '$path_info $fastcgi_path_info'
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:nginx-vhost.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    mariadb102-1:
        service_type: mariadb
        name: mariadb102-1
        settings:
            version: 10.2
            modules:
                system: []
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: db1
            MYSQL_USER: db1
            MYSQL_PASSWORD: db1
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:mariadb102-1.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    mysql57-1:
        service_type: mysql
        name: mysql57-1
        settings:
            modules:
                system: []
            version: 5.7
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: db1
            MYSQL_USER: db1
            MYSQL_PASSWORD: db1
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:mysql57-1.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    postgresql96-1:
        service_type: postgresql
        name: postgresql96-1
        settings:
            modules:
                system: []
            version: 9.6
        environment:
            POSTGRES_DB: db1
            POSTGRES_USER: db1
            POSTGRES_PASSWORD: db1
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:postgresql96-1.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    mongodb36-1:
        service_type: mongodb
        name: mongodb36-1
        settings:
            version: 3.6
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:mongodb36-1.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    redis40-1:
        service_type: redis
        name: redis40-1
        settings:
            version: 4.0
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:redis40-1.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    mailhog-1:
        service_type: mailhog
        name: mailhog-1
        settings:
            version: latest
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:mailhog-1.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    beanstalkd-1:
        service_type: beanstalkd
        name: beanstalkd-1
        settings: {  }
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:beanstalkd-1.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached

    elasticsearch621-1:
        service_type: elasticsearch
        name: elasticsearch621-1
        settings:
            version: 6.2.1
        environment:
            cluster.name: docker-cluster
            bootstrap.memory_lock: 'true'
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        networks:
            - web
        labels:
            - "traefik.frontend.rule=Host:elasticsearch621-1.localhost"
        volumes:
            -
                source: ~/www
                target: /var/www
                configuration: cached
